=== hanhan-git/itownet-ibps-run/src/main/resources/template/codegen/codegen.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="codegen" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>	
				<!--模板 -->
				<xs:element name="templates" maxOccurs="1" minOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="template">
								<xs:complexType>
									<xs:attributeGroup ref="templateAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="basepath" type="xs:string">
							<xs:annotation>
								<xs:documentation>模板的基路径.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>		
				<!-- 生成文件模版 -->
				<xs:element name="files" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:attribute name="isDefault" type="xs:boolean" default="false">
								<xs:annotation>
									<xs:documentation>
										是否默认
									</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:element name="file">
								<xs:complexType>
									<xs:attributeGroup ref="fileAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>							
				<!-- 生成文件模版 -->
				<xs:element name="dbFiles" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="file">
								<xs:complexType>
									<xs:attributeGroup ref="fileAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>							
				<xs:element name="daoFiles" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="file">
								<xs:complexType>
									<xs:attributeGroup ref="fileAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>			
				<xs:element name="domainFiles" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="file">
								<xs:complexType>
									<xs:attributeGroup ref="fileAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>								
				<xs:element name="controllerFiles" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="file">
								<xs:complexType>
									<xs:attributeGroup ref="fileAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="viewFiles" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="file">
								<xs:complexType>
									<xs:attributeGroup ref="fileAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>	
				<xs:element name="reportFiles" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="file">
								<xs:complexType>
									<xs:attributeGroup ref="fileAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="reportViewFiles" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="file">
								<xs:complexType>
									<xs:attributeGroup ref="fileAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>																																		
				<!--变量 -->
				<xs:element name="variables" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="variable" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attributeGroup ref="variableAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>									
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!--模板属性 -->
	<xs:attributeGroup name="templateAttr">
		<xs:attribute name="key" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					模版Key
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="path" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					模板路径
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	
	<!--变量属性 -->
	<xs:attributeGroup name="variableAttr">
		<xs:attribute name="name" use="required" type="xs:string">
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="comment" type="xs:string"></xs:attribute>
	</xs:attributeGroup>
	<xs:attributeGroup name="dirAttr">
		<xs:attribute name="sys" type="xs:string">
		</xs:attribute>	
		<xs:attribute name="keys" use="required" type="xs:string">
		</xs:attribute>			
		<xs:attribute name="value" type="xs:string" use="required"></xs:attribute>
	</xs:attributeGroup>	
	
	<!--文件属性-->
	<xs:attributeGroup name="fileAttr">
		<xs:attribute name="refTemplate" type="xs:string" use="required" >
			<xs:annotation>
				<xs:documentation>
					引用的模板,引用模板的ID
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="filename" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					生成的文件名称.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="dir" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					生成的文件存放的目录.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		
		<xs:attribute name="sub" type="xs:string" use="optional" default="false">
			<xs:annotation>
				<xs:documentation>
					子表生成文件
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		
		<xs:attribute name="override" type="xs:boolean" use="optional" default="false">
			<xs:annotation>
				<xs:documentation>
					是否覆盖原有文件 默认为false
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		
		<xs:attribute name="append" type="xs:boolean" use="optional">
			<xs:annotation>
					<xs:documentation>是否添加</xs:documentation>
			</xs:annotation>			
		</xs:attribute>
		<xs:attribute name="insertTag" default="&lt;!--insertbefore--&gt;">
			<xs:annotation>
					<xs:documentation>标签功能，新增的内容插在之前</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="startTag" default="start{tabname}">
			<xs:annotation>
				<xs:documentation>起始标签</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="endTag" default="end{tabname}">
			<xs:annotation>
				<xs:documentation>结束标签</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="notDelete" type="xs:boolean" use="optional">
			<xs:annotation>
					<xs:documentation>是否删除，默认是false，不用填，如果要不删除则填true</xs:documentation>
			</xs:annotation>			
		</xs:attribute>		
	</xs:attributeGroup>
	
	<xs:attributeGroup name="tableAttr">
		<xs:attribute name="tableName" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					表名
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="foreignKey" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					外键
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>

	<xs:attributeGroup name="batFleAttr">
		<xs:attribute name="refTemplate" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					引用的模板,引用模板的ID
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="filename" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					生成的文件名称.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="extName" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					文件扩展名 如: .htm
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="dir" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					生成的文件存放的目录.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="genMode" type="GenModel" use="required">
			<xs:annotation>
				<xs:documentation>
					产生一个文件/产生多个文件
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		
	</xs:attributeGroup>
	<xs:simpleType name="GenModel">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MultiFile">
				<xs:annotation>
					<xs:documentation>产生多个文件,这个时候需要填写扩展名属性</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="SingleFile">
				<xs:annotation>
					<xs:documentation>产生一个文件,这个时候需要填写文件名称</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== hanhan-git/itownet-ibps-run/src/main/resources/template/codegen/codegen.xml
<?xml version="1.0" encoding="utf-8" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="codegen.xsd">
	<templates>
		<!-- 公用文件 -->
		<template key="function"  path="function.ftl"/>
		<template key="variable"  path="variable.ftl"/>
		
		<!--单元测试相关类 -->
		<template key="baseTest"  path="test/baseTest.ftl"/>
		<template key="daoTest"  path="test/daoTest.ftl"/>
		<template key="domainTest"  path="test/domainTest.ftl"/>
						
		<!-- 持久层 persistence -->
		<template key="mapping"  path="mapping/mapping.ftl"/>
		<template key="tbl" path="entity/tbl.ftl"/>
		<template key="po" path="entity/po.ftl"/>	
			
		<template key="dao" path="dao/dao.ftl"/>
		<template key="daoImpl" path="dao/impl/daoImpl.ftl"/>
		<template key="queryDao" path="dao/queryDao.ftl"/>
		<template key="queryDaoImpl" path="dao/impl/queryDaoImpl.ftl"/>		

		<!-- 领域层 domain -->
		<template key="domain"  path="domain/domain.ftl"/>		
		<template key="repository"  path="repository/repository.ftl"/>
		<template key="repositoryImpl"  path="repository/impl/repositoryImpl.ftl"/>
		
		<!-- 接口层 api -->
		<template key="api"  path="api/service.ftl"/>
		
		<!-- 接口层 client -->
		<template key="client"  path="api/client.ftl"/>
		
		<!-- 服务层 provider -->
		<template key="provider"  path="provider/provider.ftl"/>

		<!--页面 -->
		<template key="list"  path="view/list.ftl"/>
		<template key="edit"  path="view/edit.ftl"/>
		<template key="web"  path="view/request.ftl"/>
		<template key="tree"  path="view/tree.ftl"/>
		<template key="treeEdit"  path="view/treeEdit.ftl"/>
		
		<!-- 表单渲染 -->
		<!-- 未完成，暂时注释
		<template key="formEdit"  path="form/edit.ftl"/>
		<template key="formGet"  path="form/get.ftl"/>
		 -->
	</templates>

	<!-- 
	maven
		|-src
			|-main
				|-java
				|-resources
				|-webapp
			|-test
				|-java
				|-resources
	-->
	<files isDefault="true">
		<file refTemplate="function" filename="-" dir="-" sub="true"  notDelete="true"/>						
		<file refTemplate="variable" filename="-" dir="-" sub="false"  notDelete="true"/>						
		
		<file refTemplate="baseTest" filename="{baseClass}BaseTest.java" dir="src/test/java/com/{cAlias}/{cPlatform}/{sys}" sub="false"  notDelete="true"/>						
		<!-- sub table setting -->	
		<file refTemplate="mapping" filename="{class}.map.xml" dir="src/main/resources/com/{cAlias}/{cPlatform}/{module}/persistence/mapping"  sub="true"  override="true"/>											
		<file refTemplate="tbl" filename="{class}Tbl.java" dir="src/main/java/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/entity"  sub="true" override="true"/>
		<file refTemplate="po" filename="{class}Po.java" dir="src/main/java/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/entity"  sub="true" override="true"/>
		<!-- sub table setting -->	
		<file refTemplate="dao" filename="{class}Dao.java" dir="src/main/java/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/dao" sub="true"  override="true"/>
		<file refTemplate="daoImpl" filename="{class}DaoImpl.java" dir="src/main/java/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/dao/impl" sub="true"  override="true"/>
		<file refTemplate="queryDao" filename="{class}QueryDao.java" dir="src/main/java/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/dao" sub="true"  override="true"/>
		<file refTemplate="queryDaoImpl" filename="{class}QueryDaoImpl.java" dir="src/main/java/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/dao/impl" sub="true"  override="true"/>
		<file refTemplate="daoTest" filename="{class}DaoTest.java" dir="src/test/java/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/dao" sub="true"  override="true"/>
		<!-- sub table setting -->
		<file refTemplate="domain" filename="{class}.java" dir="src/main/java/com/{cAlias}/{cPlatform}/{sys}/{module}/domain"  sub="true" override="true"/>			
		<file refTemplate="domainTest" filename="{class}Test.java" dir="src/test/java/com/{cAlias}/{cPlatform}/{sys}/{module}/domain"  sub="true"  override="true"/>
		<file refTemplate="repository" filename="{class}Repository.java" dir="src/main/java/com/{cAlias}/{cPlatform}/{sys}/{module}/repository" sub="true"   override="true"/>					
		<file refTemplate="repositoryImpl" filename="{class}RepositoryImpl.java" dir="src/main/java/com/{cAlias}/{cPlatform}/{sys}/{module}/repository/impl" sub="true"   override="true"/>
		<!-- sub table setting -->
		<file refTemplate="api" filename="I{class}Service.java" dir="src/main/java/com/{cAlias}/{cPlatform}/{sys}/{module}/api" sub="true"   override="true"/>					
		<file refTemplate="client" filename="I{class}ServiceClient.java" dir="src/main/java/com/{cAlias}/{cPlatform}/{sys}/{module}/client" sub="true"   override="true"/>					
		<!-- main table setting -->																					
		<file refTemplate="provider" filename="{class}Provider.java" dir="src/main/java/com/{cAlias}/{cPlatform}/{sys}/{module}/provider" sub="false"  override="true"/>
		<!-- main table setting -->																		
		<file refTemplate="web" filename="{classVar}.js" dir="src/api/{sys}/{module}" sub="false"  override="true"/>
		<file refTemplate="list" filename="list.vue" dir="src/views/{sys}/{module}/{classVar}" sub="false"  override="true"/>
		<file refTemplate="edit" filename="edit.vue" dir="src/views/{sys}/{module}/{classVar}" sub="false"  override="true"/>
		<file refTemplate="tree" filename="manage.vue" dir="src/views/{sys}/{module}/{classVar}" sub="false"  override="true"/>
		<file refTemplate="treeEdit" filename="tree-edit.vue" dir="src/views/{sys}/{module}/{classVar}" sub="false"  override="true"/>
		
		<!-- 
		<file refTemplate="formEdit" filename="{classVar}FormEdit.jsp" dir="src/main/webapp/WEB-INF/view/{app}/{module}" sub="false"  override="true"/>
		<file refTemplate="formGet" filename="{classVar}FormGet.jsp" dir="src/main/webapp/WEB-INF/view/{app}/{module}" sub="false"  override="true"/>
		 -->
	</files>
	
	<!-- 
	javaWeb
		|-src
		|-resources
		|-web
	-->
	<files isDefault="false">
		<file refTemplate="function" filename="-" dir="-" sub="true"  notDelete="true"/>						
		<file refTemplate="variable" filename="-" dir="-" sub="false"  notDelete="true"/>						
		
		<file refTemplate="baseTest" filename="{baseClass}BaseTest.java" dir="src/com/{cAlias}/{cPlatform}/{sys}" sub="false"  notDelete="true"/>						
		<!-- sub table setting -->	
		<file refTemplate="mapping" filename="{class}.map.xml" dir="resources/com/{cAlias}/{cPlatform}/{module}/persistence/mapping"  sub="true"  override="true"/>											
		<file refTemplate="tbl" filename="{class}Tbl.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/entity"  sub="true" override="true"/>
		<file refTemplate="po" filename="{class}Po.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/entity"  sub="true" override="true"/>
		<!-- sub table setting -->	
		<file refTemplate="dao" filename="{class}Dao.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/dao" sub="true"  override="true"/>
		<file refTemplate="daoImpl" filename="{class}DaoImpl.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/dao/impl" sub="true"  override="true"/>
		<file refTemplate="queryDao" filename="{class}QueryDao.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/dao" sub="true"  override="true"/>
		<file refTemplate="queryDaoImpl" filename="{class}QueryDaoImpl.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/dao/impl" sub="true"  override="true"/>
		<file refTemplate="daoTest" filename="{class}DaoTest.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/persistence/dao" sub="true"  override="true"/>
		<!-- sub table setting -->
		<file refTemplate="domain" filename="{class}.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/domain"  sub="true" override="true"/>			
		<file refTemplate="domainTest" filename="{class}Test.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/domain"  sub="true"  override="true"/>
		<file refTemplate="repository" filename="{class}Repository.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/repository" sub="true"   override="true"/>					
		<file refTemplate="repositoryImpl" filename="{class}RepositoryImpl.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/repository/impl" sub="true"   override="true"/>
		<!-- sub table setting -->
		<file refTemplate="api" filename="I{class}Service.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/api" sub="true"   override="true"/>					
		<file refTemplate="client" filename="I{class}ServiceClient.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/client" sub="true"   override="true"/>					
		<!-- main table setting -->																					
		<file refTemplate="provider" filename="{class}Provider.java" dir="src/com/{cAlias}/{cPlatform}/{sys}/{module}/provider" sub="false"  override="true"/>
		<!-- main table setting -->																		
		<!-- 
		<file refTemplate="tree" filename="{classVar}Tree.jsp" dir="web/WEB-INF/view/{app}/{module}" sub="false"  override="true"/>
		<file refTemplate="list" filename="{classVar}List.jsp" dir="web/WEB-INF/view/{app}/{module}" sub="false"  override="true"/>
		<file refTemplate="edit" filename="{classVar}Edit.jsp" dir="web/WEB-INF/view/{app}/{module}" sub="false"  override="true"/>
		<file refTemplate="flowEdit" filename="{classVar}FlowEdit.jsp" dir="web/WEB-INF/view/{app}/{module}" sub="false"  override="true"/>
		<file refTemplate="get" filename="{classVar}Get.jsp" dir="web/WEB-INF/view/{app}/{module}" sub="false"  override="true"/>
		<file refTemplate="web" filename="{classVar}.js" dir="web/js/{cAlias}/{app}/{module}" sub="false"  override="true"/>
		
		<file refTemplate="formEdit" filename="{classVar}FormEdit.jsp" dir="web/WEB-INF/view/{app}/{module}" sub="false"  override="true"/>
		<file refTemplate="formGet" filename="{classVar}FormGet.jsp" dir="web/WEB-INF/view/{app}/{module}" sub="false"  override="true"/>
		 -->
	</files>
	
	<!-- 
	javaWeb
		|-src
		|-resources
		|-webapp
	-->
	<files isDefault="false">
