=== hanhan-git/itownet-ibps-run/target/itownet-ibps-run-exclude/conf/taskActionPlugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.bpmhome.cn/bpm/plugin/taskAction"
    targetNamespace="http://www.bpmhome.cn/bpm/plugin/taskAction" elementFormDefault="qualified">
    <xs:element name="taskAction">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="0" name="description">
                	<xs:complexType>
                		<xs:attribute name="value" type="xs:string" use="required"/>
                	</xs:complexType>
                </xs:element>
                <xs:element maxOccurs="1" minOccurs="0" name="handlerClass">
                	<xs:annotation>
                		<xs:documentation>这个只是审批的时候需要(比如同意,反对)</xs:documentation>
                	</xs:annotation>
                	<xs:complexType>
                		<xs:attribute name="value" type="xs:string" use="required"/>
                	</xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="supportType" type="supportType"  use="required"/>
            <xs:attribute name="actionType" type="actionType"  use="required"/>
            <xs:attribute name="script" type="xs:boolean"  use="required" >
            	<xs:annotation>
            		<xs:documentation>是否支持脚本</xs:documentation>
            	</xs:annotation>
            </xs:attribute>
            <xs:attribute name="init" type="xs:boolean">
            	<xs:annotation>
            		<xs:documentation>初始化默认</xs:documentation>
            	</xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="supportType">
    	<xs:restriction base="xs:string">
    		<xs:enumeration value="usertask">
    			<xs:annotation>
    				<xs:documentation>用户任务专用</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		<xs:enumeration value="signtask">
    			<xs:annotation>
    				<xs:documentation>会签任务专用</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		<xs:enumeration value="none">
    			<xs:annotation>
    				<xs:documentation>都不支持</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		<xs:enumeration value="both">
    			<xs:annotation>
    				<xs:documentation>支持普通用户任务和会签任务</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		<xs:enumeration value="start">
    			<xs:annotation>
    				<xs:documentation>起始节点</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		<xs:enumeration value="all">
    			<xs:annotation>
    				<xs:documentation>所有节点</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    	</xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="actionType">
    	<xs:restriction base="xs:string">
    		<xs:enumeration value="approve">
    			<xs:annotation>
    				<xs:documentation>审批</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		<xs:enumeration value="assist">
    			<xs:annotation>
    				<xs:documentation>辅助</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		<xs:enumeration value="reject">
    			<xs:annotation>
    				<xs:documentation>驳回</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		<xs:enumeration value="rejectToPrevious">
    			<xs:annotation>
    				<xs:documentation>驳回上一步</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		<xs:enumeration value="rejectToStart">
    			<xs:annotation>
    				<xs:documentation>驳回至发起人</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		<xs:enumeration value="revoke">
    			<xs:annotation>
    				<xs:documentation>撤销</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		<xs:enumeration value="commu">
    			<xs:annotation>
    				<xs:documentation>沟通</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		<xs:enumeration value="trans">
    			<xs:annotation>
    				<xs:documentation>任务流转</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    		
    		<xs:enumeration value="other">
    			<xs:annotation>
    				<xs:documentation>其他</xs:documentation>
    			</xs:annotation>
    		</xs:enumeration>
    	</xs:restriction>
    </xs:simpleType>
    <xs:element name="taskActions">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="taskAction"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="nameUnique">
            <xs:selector xpath="taskAction"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== hanhan-git/itownet-ibps-run/target/itownet-ibps-run-exclude/conf/taskActionPlugins.xml
<?xml version="1.0" encoding="UTF-8"?>
<taskActions xmlns="http://www.bpmhome.cn/bpm/plugin/taskAction"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.bpmhome.cn/bpm/plugin/taskAction taskActionPlugin.xsd"
    namesxmlns="http://www.bpmhome.cn/bpm/plugin/taskAction">
    
    <taskAction name="lock" supportType="both" actionType="assist" script="false" init="true">
        <description value="锁定"/>
        <handlerClass value=""/>
    </taskAction>
    
    <taskAction name="unlock" supportType="both" actionType="assist" script="false" init="true">
        <description value="解锁"/>
        <handlerClass value=""/>
    </taskAction>
    
    <taskAction name="forceUnlock" supportType="both" actionType="assist" script="false" init="false">
        <description value="强制解锁"/>
        <handlerClass value=""/>
    </taskAction>
    
    <taskAction name="agree" supportType="both" actionType="approve" script="true" init="true">
        <description value="同意"/>
        <handlerClass value="taskActionAgreeHandler"/>
    </taskAction>
    
    <taskAction name="save" supportType="both" actionType="other" script="true" init="true">
        <description value="保存"/>
        <handlerClass value="taskActionNoneHandler"/>
    </taskAction>
 
    <taskAction name="abandon" supportType="signtask" actionType="approve" script="true" init="false">
        <description value="弃权"/>
        <handlerClass value="taskActionAgreeHandler"/>
    </taskAction>
    
    <taskAction name="oppose" supportType="both" actionType="approve" script="true" init="false">
        <description value="反对"/>
        <handlerClass value="taskActionAgreeHandler"/>
    </taskAction>
    
    <!-- 
    <taskAction name="agreeTrans" supportType="both" actionType="trans" script="true" init="true">
        <description value="同意(流转)"/>
        <handlerClass value="taskActionTransHandler"/>
    </taskAction>
    
    <taskAction name="opposeTrans" supportType="both" actionType="trans" script="true" init="true">
        <description value="反对(流转)"/>
        <handlerClass value="taskActionTransHandler"/>
    </taskAction>
    
    <taskAction name="commu" supportType="both" actionType="commu" script="true" init="true">
        <description value="沟通反馈"/>
        <handlerClass value="taskActionCommuHandler"/>
    </taskAction>
    
    <taskAction name="startCommu" supportType="both" actionType="other" script="false" init="true">
    	<description value="发起沟通"/>
    	<handlerClass value=""/>
    </taskAction>
    
    <taskAction name="startTrans" supportType="usertask" actionType="other" script="false" init="true">
    	<description value="发起流转"/>
    	<handlerClass value=""/>
    </taskAction>
    -->
     
    <taskAction name="reject" supportType="both" actionType="reject" script="true" init="true">
        <description value="驳回"/>
        <handlerClass value="taskActionRejectHandler"/>
    </taskAction>
    
    <taskAction name="rejectToStart" supportType="both" actionType="rejectToStart" script="true" init="true">
        <description value="驳回发起人"/> 
        <handlerClass value="taskActionRejectToStartHandler"/>
    </taskAction>
    
    <taskAction name="rejectToPrevious" supportType="both" actionType="rejectToPrevious" script="true" init="true">
        <description value="驳回上一步"/> 
        <handlerClass value="taskActionRejectToPreviousHandler"/>
    </taskAction>
    
    <!-- 其他节点和界面按钮相关 -->
    
    <taskAction name="startFlow" supportType="start" actionType="other" script="true" init="true">
    	<description value="启动"/>
    	<handlerClass value=""/>
    </taskAction>
    
  	<taskAction name="saveDraft" supportType="start" actionType="other" script="true" init="true">
    	<description value="保存草稿"/>
    	<handlerClass value=""/>
    </taskAction>
    
    <taskAction name="delegate" supportType="both" actionType="other" script="false" init="true">
    	<description value="转办"/>
    	<handlerClass value=""/>
    </taskAction>
     
    <taskAction name="addSign" supportType="signtask" actionType="other" script="false" init="true">
    	<description value="补签"/>
    	<handlerClass value=""/>
    </taskAction>
    
   <taskAction name="approvalHistory" supportType="both" actionType="approve" script="false" init="true">
    	<description value="审批历史"/>
    	<handlerClass value=""/>
    </taskAction>
    
    <taskAction name="flowImage" supportType="all" actionType="other" script="false" init="true">
    	<description value="流程图"/>
    	<handlerClass value=""/>
    </taskAction>

	<taskAction name="print" supportType="all" actionType="other" script="false" init="true">
    	<description value="打印"/>
    	<handlerClass value=""/>
    </taskAction>
    
    <taskAction name="endProcess" supportType="both" actionType="other" script="true" init="true">
    	<description value="终止流程"/>
    	<handlerClass value=""/>
    </taskAction>
    
    <taskAction name="suspendProcess" supportType="both" actionType="other" script="true" init="true">
    	<description value="挂起"/>
    	<handlerClass value=""/>
    </taskAction>
    
    <taskAction name="recoverProcess" supportType="both" actionType="other" script="true" init="true">
    	<description value="恢复"/>
    	<handlerClass value=""/>
    </taskAction>
    
    <taskAction name="revoke" supportType="none" actionType="revoke" script="false" init="false">
        <description value="撤销"/>
        <handlerClass value="taskActionRevokeHandler"/>
    </taskAction>
    
    <!--
    <taskAction name="trigger" supportType="both" actionType="trigger" script="true" init="false">
        <description value="触发流程"/>
        <handlerClass value="taskActionTriggerHandler"/>
    </taskAction>
    -->
    
    <taskAction name="custom" supportType="both" actionType="custom" script="true" init="false">
        <description value="[自定义按钮]"/>
        <handlerClass value="taskActionCustomHandler"/>
    </taskAction>
    
</taskActions>
